name: Upload Website

on:
  push:
    branches:
    - deploy

jobs:
  deploy:
    runs-on: self-hosted
 
    steps:
    - uses: actions/checkout@main

    - name: Take backup 
      run: |
       ssh -t ubuntu@"${{ secrets.IP_ADDRESS }}" " 'cp' -fR /home/ubuntu/node-app/* /home/ubuntu/backup/ "
       echo "file Updated"

    - name: copy to Deploy server 
      run: |
       rsync -zhvr . ubuntu@"${{ secrets.IP_ADDRESS }}":/home/ubuntu/node-app/
       echo "file Updated"
      
    - name: Install Packages
      run: |
       ssh -t ubuntu@"${{ secrets.IP_ADDRESS }}" 'cd /home/ubuntu/node-app && npm i'
       echo "Packages Installed"

    - name: Start Application
      run: |
       ssh -t ubuntu@"${{ secrets.IP_ADDRESS }}" 'cd /home/ubuntu/node-app && pm2 restart app'
       echo "Application is Live"   
        
