name: Upload Website

on:
  push:
    branches:
    - deploy

jobs:
  deploy:
    runs-on: self-hosted
    env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@main
    - name: copy to Deploy server 
      run: |
       rsync -zhvr . ubuntu@3.83.220.131:/home/ubuntu/node-app/
       echo "file Updated"
      
   # - name: cloud front
   #   run: |
   #    aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_ID" --paths '/*'
   #   echo "Website updated"
        
