name: Upload Website

on:
  push:
    branches:
    - deploy

jobs:
  deploy:
    runs-on: self-hosted
    env:
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@main


    - name: copy to Deploy server 
      run: |
       rm -rf my-github-repo
       ssh -t ubuntu@35.174.116.224 "git clone --branch deploy  https://github.com/Patel-Viraj/my-github-repo.git"
       echo "file Updated"
       echo "file Updated"
      
    - name: Install Packages
      run: |
       ssh -t ubuntu@35.174.116.224 'cd /home/ubuntu/my-github-repo && npm i'
       echo "Packages Installed"

    - name: Start Application
      run: |
       ssh -t ubuntu@35.174.116.224 'cd /home/ubuntu/my-github-repo && pm2 restart app'
       echo "Application is Live"   
        
